import json
from groq import Groq
from app.config import settings

client = Groq(api_key=settings.groq_api_key)

def run(state: dict) -> dict:
    ticker = state["ticker"]
    news = state.get("news", [])
    financials = state.get("financials", {})
    sentiment = state.get("sentiment", {})

    headlines = "\n".join([f"- {a['title']}" for a in news])
    fin_str = "\n".join([f"{k}: {v}" for k, v in financials.items()])

    prompt = f"""You are a senior financial research analyst.
Write a structured research report for {ticker} using the data below.

FINANCIALS:
{fin_str}

RECENT NEWS:
{headlines}

SENTIMENT ANALYSIS:
Label: {sentiment.get('label', 'N/A')}
Score: {sentiment.get('score', 'N/A')} (scale: -1 bearish to +1 bullish)
Reasoning: {sentiment.get('reasoning', 'N/A')}

Write the report in this exact markdown structure:

# {ticker} Research Report

## Executive Summary
<2-3 sentence overview of the company and current situation>

## Key Financial Metrics
<bullet points of the most important numbers>

## Sentiment Analysis
<what the news sentiment means for the stock>

## Risk Factors
<2-3 key risks an investor should know>

## Outlook
<short-term outlook based on all available data>

---
*Report generated by AI Financial Research Agent*
"""

    try:
        res = client.chat.completions.create(
            model=settings.groq_model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3
        )
        report_md = res.choices[0].message.content.strip()
        print(f"[report_agent] report generated for {ticker} ({len(report_md)} chars)")
        return {"report_md": report_md}

    except Exception as e:
        print(f"[report_agent] error: {e}")
        return {"report_md": "", "error_msg": str(e)}